name: Test

on:
  push:
    paths:
      - src/**
      - tests/**
      - '**/Directory.Build.*'

  pull_request:
    paths:
      - src/**
      - tests/**
      - '**/Directory.Build.*'

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: dotnet build
        run: dotnet build
        working-directory: tests/BiDaFlow.Tests

      - name: dotnet test
        run: dotnet test --no-restore --verbosity normal
        working-directory: tests/BiDaFlow.Tests
